[2025-01-05T21:51:09.876+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T21:51:09.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:51:08.805637+00:00 [queued]>
[2025-01-05T21:51:09.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:51:08.805637+00:00 [queued]>
[2025-01-05T21:51:09.896+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-05T21:51:09.904+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_db> on 2025-01-05 21:51:08.805637+00:00
[2025-01-05T21:51:09.911+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=906) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T21:51:09.909+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'load_db', 'manual__2025-01-05T21:51:08.805637+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmpquta6pnb']
[2025-01-05T21:51:09.911+0000] {standard_task_runner.py:63} INFO - Started process 911 to run task
[2025-01-05T21:51:09.911+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask load_db
[2025-01-05T21:51:09.935+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:51:08.805637+00:00 [running]> on host 6d9883a799ac
[2025-01-05T21:51:09.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='load_db' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T21:51:08.805637+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T21:51:08.805637+00:00'
[2025-01-05T21:51:09.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T21:51:10.113+0000] {logging_mixin.py:188} INFO - Нет данных для загрузки
[2025-01-05T21:51:10.113+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-05T21:51:10.114+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T21:51:10.118+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_banking_tinkoff, task_id=load_db, run_id=manual__2025-01-05T21:51:08.805637+00:00, execution_date=20250105T215108, start_date=20250105T215109, end_date=20250105T215110
[2025-01-05T21:51:10.143+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-05T21:51:10.151+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T21:51:10.152+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
