[2025-01-05T16:51:08.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T16:51:08.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T16:51:07.066768+00:00 [queued]>
[2025-01-05T16:51:08.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T16:51:07.066768+00:00 [queued]>
[2025-01-05T16:51:08.483+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T16:51:08.488+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): file_processing> on 2025-01-05 16:51:07.066768+00:00
[2025-01-05T16:51:08.492+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'file_processing', 'manual__2025-01-05T16:51:07.066768+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmp7u70fp48']
[2025-01-05T16:51:08.493+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask file_processing
[2025-01-05T16:51:08.493+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T16:51:08.494+0000] {standard_task_runner.py:63} INFO - Started process 245 to run task
[2025-01-05T16:51:08.518+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T16:51:07.066768+00:00 [running]> on host 928815d407f9
[2025-01-05T16:51:08.551+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='file_processing' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T16:51:07.066768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T16:51:07.066768+00:00'
[2025-01-05T16:51:08.551+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T16:51:08.705+0000] {xcom.py:675} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2025-01-05T16:51:08.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T16:51:08.706+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_banking_tinkoff.py", line 45, in file_processing
    kwargs['ti'].xcom_push(key='to_db', value=to_db.sort_values('Дата операции').to_dict())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2025-01-05T16:51:08.712+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_banking_tinkoff, task_id=file_processing, run_id=manual__2025-01-05T16:51:07.066768+00:00, execution_date=20250105T165107, start_date=20250105T165108, end_date=20250105T165108
[2025-01-05T16:51:08.717+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task file_processing (Object of type Timestamp is not JSON serializable; 245)
[2025-01-05T16:51:08.725+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-05T16:51:08.733+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T16:51:08.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
