[2025-01-05T15:42:49.151+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T15:42:49.166+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:42:48.219125+00:00 [queued]>
[2025-01-05T15:42:49.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:42:48.219125+00:00 [queued]>
[2025-01-05T15:42:49.169+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T15:42:49.175+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): file_check> on 2025-01-05 15:42:48.219125+00:00
[2025-01-05T15:42:49.178+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'file_check', 'manual__2025-01-05T15:42:48.219125+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmpn4tn4enb']
[2025-01-05T15:42:49.180+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask file_check
[2025-01-05T15:42:49.180+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3139) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T15:42:49.181+0000] {standard_task_runner.py:63} INFO - Started process 3141 to run task
[2025-01-05T15:42:49.200+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:42:48.219125+00:00 [running]> on host 0509704c18d8
[2025-01-05T15:42:49.237+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='file_check' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T15:42:48.219125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T15:42:48.219125+00:00'
[2025-01-05T15:42:49.237+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T15:42:49.252+0000] {logging_mixin.py:188} INFO - Папка ../finflow/data/banking/alfa/new не существует
[2025-01-05T15:42:49.252+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-05T15:42:49.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T15:42:49.364+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_banking_tinkoff, task_id=file_check, run_id=manual__2025-01-05T15:42:48.219125+00:00, execution_date=20250105T154248, start_date=20250105T154249, end_date=20250105T154249
[2025-01-05T15:42:49.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-05T15:42:49.425+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T15:42:49.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
