[2025-01-05T20:45:48.097+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T20:45:48.109+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:45:46.301961+00:00 [queued]>
[2025-01-05T20:45:48.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:45:46.301961+00:00 [queued]>
[2025-01-05T20:45:48.112+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T20:45:48.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): file_processing> on 2025-01-05 20:45:46.301961+00:00
[2025-01-05T20:45:48.121+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'file_processing', 'manual__2025-01-05T20:45:46.301961+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmp27zgi07r']
[2025-01-05T20:45:48.122+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask file_processing
[2025-01-05T20:45:48.122+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T20:45:48.123+0000] {standard_task_runner.py:63} INFO - Started process 195 to run task
[2025-01-05T20:45:48.141+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:45:46.301961+00:00 [running]> on host ab28a6598ee5
[2025-01-05T20:45:48.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='file_processing' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T20:45:46.301961+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T20:45:46.301961+00:00'
[2025-01-05T20:45:48.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T20:45:48.283+0000] {python.py:237} INFO - Done. Returned value was:            Дата операции  ...              load_dt
0    31.12.2024 17:39:21  ...  2025-01-05T20:45:48
1    31.12.2024 17:38:42  ...  2025-01-05T20:45:48
2    31.12.2024 17:37:14  ...  2025-01-05T20:45:48
3    31.12.2024 17:28:45  ...  2025-01-05T20:45:48
4    30.12.2024 20:43:40  ...  2025-01-05T20:45:48
..                   ...  ...                  ...
104  01.12.2024 19:43:31  ...  2025-01-05T20:45:48
105  01.12.2024 12:09:00  ...  2025-01-05T20:45:48
106  01.12.2024 12:03:44  ...  2025-01-05T20:45:48
107  01.12.2024 11:44:41  ...  2025-01-05T20:45:48
108  01.12.2024 11:44:26  ...  2025-01-05T20:45:48

[109 rows x 16 columns]
[2025-01-05T20:45:48.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T20:45:48.317+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_banking_tinkoff, task_id=file_processing, run_id=manual__2025-01-05T20:45:46.301961+00:00, execution_date=20250105T204546, start_date=20250105T204548, end_date=20250105T204548
[2025-01-05T20:45:48.349+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-05T20:45:48.357+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T20:45:48.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
